name: dev frontend CI

on:
  push:
    branches:
      - 'master'
    paths:
      - 'apps/platform/**'
      - 'apps/admin/**'
      - 'apps/portal/**'
      - 'apps/storybook/**'
      - 'packages/**'
  workflow_dispatch:
    inputs:
      app:
        description: '배포할 앱'
        required: true
        type: choice
        options:
          - platform
          - admin
          - portal
          - storybook

jobs:
  # Path별 변경 사항 감지
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      platform: ${{ steps.filter.outputs.platform }}
      admin: ${{ steps.filter.outputs.admin }}
      portal: ${{ steps.filter.outputs.portal }}
      storybook: ${{ steps.filter.outputs.storybook }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        if: github.event_name == 'push'
        with:
          filters: |
            platform:
              - 'apps/platform/**'
            admin:
              - 'apps/admin/**'
            portal:
              - 'apps/portal/**'
            storybook:
              - 'apps/storybook/**'
            packages:
              - 'packages/**'
  build:
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      matrix:
        app: [platform, admin, portal, storybook]
        include:
          - app: platform
            package: platform
            options: "--delete"
          - app: admin
            package: platform_back_office
          - app: portal
            package: portal
            options: "--delete"
          - app: storybook
            package: storybook
    steps:
      - uses: actions/checkout@v4

      # Build with matrix
      - name: Build ${{ matrix.app }}
        if: ${{ ( github.event_name == 'push' && ( needs.changes.outputs[matrix.app] == 'true' || needs.changes.outputs.packages == 'true' ) ) || ( github.event_name == 'workflow_dispatch' && github.event.inputs.app == matrix.app ) }}
        run: echo "options:${{ matrix.options }} app:${{ matrix.app }}"

  finally:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo hi