name: dev frontend CI

on:
  push:
    branches:
      - 'master'
    paths:
      - 'apps/platform/**'
      - 'apps/admin/**'
      - 'apps/portal/**'
      - 'apps/storybook/**'
  workflow_dispatch:
    inputs:
      app:
        description: '배포할 앱'
        required: true
        type: choice
        options:
          - platform
          - admin
          - portal
          - storybook

jobs:
  # Path별 변경 사항 감지
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      platform: ${{ steps.filter.outputs.platform }}
      admin: ${{ steps.filter.outputs.admin }}
      portal: ${{ steps.filter.outputs.portal }}
      storybook: ${{ steps.filter.outputs.storybook }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        if: github.event_name == 'push'
        with:
          filters: |
            platform:
              - 'apps/platform/**'
            admin:
              - 'apps/admin/**'
            portal:
              - 'apps/portal/**'
            storybook:
              - 'apps/storybook/**'
  build:
    runs-on: ubuntu-latest
    needs: changes
    steps:
      - uses: actions/checkout@v4

      # Build apps
      - name: build admin
        if: ${{ ( github.event_name == 'push' && needs.changes.outputs.admin == 'true' ) || (github.event_name == 'workflow_dispatch' && github.event.inputs.app == 'admin') }}
        run: echo 'admin'
      - name: build platform
        if: ${{ ( github.event_name == 'push' && needs.changes.outputs.platform == 'true' ) || (github.event_name == 'workflow_dispatch' && github.event.inputs.app == 'platform') }}
        run: echo 'platform'
      - name: build portal
        if: ${{ ( github.event_name == 'push' && needs.changes.outputs.portal == 'true' ) || (github.event_name == 'workflow_dispatch' && github.event.inputs.app == 'portal') }}
        run: echo 'portal'
      - name: build storybook
        if: ${{ ( github.event_name == 'push' && needs.changes.outputs.storybook == 'true' ) || (github.event_name == 'workflow_dispatch' && github.event.inputs.app == 'storybook') }}
        run: echo 'storybook'

