name: "Submit to Web Store"
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  pre-publish:
    runs-on: ubuntu-latest
    outputs:
      is_submittable: ${{ steps.check.outputs.is_submittable }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Check condition
        id: check
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "is_submittable=true" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == "push" ]; then
            # Commit message should be [DATAC-1626] Bump version of packages
            if [[ $(git log -1 --pretty=%B) == *"[AB-000] Bump version of packages"* ]]; then
              echo "is_submittable=true" >> $GITHUB_OUTPUT
            else
              echo "is_submittable=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "is_submittable=false" >> $GITHUB_OUTPUT
          fi

  publish:
    runs-on: ubuntu-latest
    needs: pre-publish
    if: needs.pre-publish.outputs.is_submittable == 'true'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.12"